### PR TITLE
Casing copyright

### PR DESCRIPTION
**Pull request by DMaffAD**
Updated npm packages to latest.
Changed readme to give fuller install and build instructions.
Added copyright and licence info to the head of each file.
Updated file folder names to use Upper camel for react components and hyphen casing for all other filenames.
Fixed unit-test.

### CODE REVIEW

**Comment by george-roberts** [comment]
Very small comment on the ReadMe, can we update it to say the 'New Debugger' setting needs to be enabled in the user preferences? I got stuck on this for quite a while today

**Comment by george-roberts** [comment]
The new debugger doesn't seem to work without a special post.exe. We should include this in the repo so that it can be 'auto selected'

**Comment by DMaffAD** [comment]
> Very small comment on the ReadMe, can we update it to say the 'New Debugger' setting needs to be enabled in the user preferences? I got stuck on this for quite a while today

That's been updated.

**Comment by DMaffAD** [comment]
> The new debugger doesn't seem to work without a special post.exe. We should include this in the repo so that it can be 'auto selected'

The post with debugging functionality has been added to the repo and will be part of the vsix. Instructions have been added to help the user setup this post.

**Pull request merged**
